const FULL_MENU = {
  coffee: [
    {
      name: "Irish coffee",
      image: "./assets/images/coffee/coffee-1.png",
      info: "Fragrant black coffee with Jameson Irish whiskey and whipped milk",
      price: 7,
      alt: "Irish coffee",
      type: "coffee",
    },
    {
      name: "Kahlua coffee",
      image: "./assets/images/coffee/coffee-2.png",
      info: "Classic coffee with milk and Kahlua liqueur under a cap of frothed milk",
      price: 7,
      alt: "Kahlua coffee",
      type: "coffee",
    },
    {
      name: "Honey raf",
      image: "./assets/images/coffee/coffee-3.png",
      info: "Espresso with frothed milk, cream and aromatic honey",
      price: 5.5,
      alt: "Honey raf",
      type: "coffee",
    },
    {
      name: "Ice cappuccino",
      image: "./assets/images/coffee/coffee-4.png",
      info: "Cappuccino with soft thick foam in summer version with ice",
      price: 5,
      alt: "Ice cappuccino",
      type: "coffee",
    },
    {
      name: "Espresso",
      image: "./assets/images/coffee/coffee-5.png",
      info: "Classic black coffee",
      price: 4.5,
      alt: "Espresso",
      type: "coffee",
    },
    {
      name: "Latte",
      image: "./assets/images/coffee/coffee-6.png",
      info: "Espresso coffee with the addition of steamed milk and dense milk foam",
      price: 5.5,
      alt: "Latte",
      type: "coffee",
    },
    {
      name: "Latte macchiato",
      image: "./assets/images/coffee/coffee-7.png",
      info: "Espresso with frothed milk and chocolate",
      price: 5.5,
      alt: "Latte macchiato",
      type: "coffee",
    },
    {
      name: "Coffee with cognac",
      image: "./assets/images/coffee/coffee-8.png",
      info: "Fragrant black coffee with cognac and whipped cream",
      price: 6.5,
      alt: "Coffee with cognac",
      type: "coffee",
    },
  ],
  tea: [
    {
      name: "Moroccan",
      image: "./assets/images/tea/tea-1.png",
      info: "Fragrant black tea with the addition of tangerine, cinnamon, honey, lemon and mint",
      price: 4.5,
      alt: "Moroccan tea",
      type: "tea",
    },
    {
      name: "Ginger",
      image: "./assets/images/tea/tea-2.png",
      info: "Original black tea with fresh ginger, lemon and honey",
      price: 5,
      alt: "Ginger tea",
      type: "tea",
    },
    {
      name: "Cranberry",
      image: "./assets/images/tea/tea-3.png",
      info: "Invigorating black tea with cranberry and honey",
      price: 5,
      alt: "Cranberry tea",
      type: "tea",
    },
    {
      name: "Sea buckthorn",
      image: "./assets/images/tea/tea-4.png",
      info: "Toning sweet black tea with sea buckthorn, fresh thyme and cinnamon",
      price: 5.5,
      alt: "Sea buckthorn tea",
      type: "tea",
    },
  ],
  dessert: [
    {
      name: "Marble cheesecake",
      image: "./assets/images/dessert/dessert-1.png",
      info: "Philadelphia cheese with lemon zest on a light sponge cake and red currant jam",
      price: 3.5,
      alt: "Marble cheesecake",
      type: "dessert",
    },
    {
      name: "Red velvet",
      image: "./assets/images/dessert/dessert-2.png",
      info: "Layer cake with cream cheese frosting",
      price: 4,
      alt: "Red velvet",
      type: "dessert",
    },
    {
      name: "Cheesecakes",
      image: "./assets/images/dessert/dessert-3.png",
      info: "Soft cottage cheese pancakes with sour cream and fresh berries and sprinkled with powdered sugar",
      price: 4.5,
      alt: "Cheesecakes",
      type: "dessert",
    },
    {
      name: "Creme brulee",
      image: "./assets/images/dessert/dessert-4.png",
      info: "Delicate creamy dessert in a caramel basket with wild berries",
      price: 4,
      alt: "Creme brulee",
      type: "dessert",
    },
    {
      name: "Pancakes",
      image: "./assets/images/dessert/dessert-5.png",
      info: "Tender pancakes with strawberry jam and fresh strawberries",
      price: 4.5,
      alt: "Pancakes",
      type: "dessert",
    },
    {
      name: "Honey cake",
      image: "./assets/images/dessert/dessert-6.png",
      info: "Classic honey cake with delicate custard",
      price: 4.5,
      alt: "Honey cake",
      type: "dessert",
    },
    {
      name: "Chocolate cake",
      image: "./assets/images/dessert/dessert-7.png",
      info: "Cake with hot chocolate filling and nuts with dried apricots",
      price: 5.5,
      alt: "Chocolate cake",
      type: "dessert",
    },
    {
      name: "Black forest",
      image: "./assets/images/dessert/dessert-8.png",
      info: "A combination of thin sponge cake with cherry jam and light chocolate mousse",
      price: 6.5,
      alt: "Black forest",
      type: "dessert",
    },
  ],
};

const PRODUCT_CONFIG = {
  coffee: {
    sizes: [
      {
        size: "S",
        value: "200",
        unit: "ml",
        checked: true,
        sizePrice: 0,
      },
      {
        size: "M",
        value: "300",
        unit: "ml",
        checked: false,
        sizePrice: 0.5,
      },
      {
        size: "L",
        value: "400",
        unit: "ml",
        checked: false,
        sizePrice: 1,
      },
    ],
    additives: ["Sugar", "Cinnamon", "Syrup"],
  },
  tea: {
    sizes: [
      {
        size: "S",
        value: "200",
        unit: "ml",
        checked: true,
        sizePrice: 0,
      },
      {
        size: "M",
        value: "300",
        unit: "ml",
        checked: false,
        sizePrice: 0.5,
      },
      {
        size: "L",
        value: "400",
        unit: "ml",
        checked: false,
        sizePrice: 1,
      },
    ],
    additives: ["Sugar", "Lemon", "Syrup"],
  },
  dessert: {
    sizes: [
      {
        size: "S",
        value: "50",
        unit: "g",
        checked: true,
        sizePrice: 0,
      },
      {
        size: "M",
        value: "100",
        unit: "g",
        checked: false,
        sizePrice: 0.5,
      },
      {
        size: "L",
        value: "200",
        unit: "g",
        checked: false,
        sizePrice: 1,
      },
    ],
    additives: ["Berries", "Nuts", "Jam"],
  },
};
