export const easyGame = {
  heart: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  crown: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  anchor: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  flower: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  wineglass: [
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
};

export const mediumGame = {
  heart: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  crown: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
  ],
  anchor: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  flower: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
  wineglass: [
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
};

export const hardGame = {
  heart: [
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
    [
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 1, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
      { value: 0, selected: false, crossed: false },
    ],
  ],
};
